name: BlizzHungergames
version: 0.1
main: fr.blizzteam.hg.HungerGames
description: Plugin HungerGames Blizz Team!
 
commands:
    help:
        usage: /<command>
        description: View help
    who:
        usage: /<command>
        description: view player
       
permissions:
    motd.set:
        description: Use the setmotd command to change the MOTD.
        default: op