name: BlizzHungergames
version: 0.1
main: fr.blizzteam.hg.HungerGames
description: Plugin HungerGames Blizz Team!
 
commands:
    test:
        usage: /<command>
        description: View help
    help:
        usage: /<command>
        description: view player
